CREATE TABLE countries(
	id SERIAL,
	country VARCHAR(50),
	PRIMARY KEY (id)
);

CREATE TABLE users(
	id uuid DEFAULT gen_random_uuid(),
	country INT,
	name VARCHAR(50),
	last_name VARCHAR(50),
	user_name VARCHAR(50),
	phone VARCHAR(20),
	email VARCHAR(50),
	password VARCHAR(70),
	photo VARCHAR(225), 
	bio VARCHAR(150),
	birthdate DATE,
	gender VARCHAR(10),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP, 
	PRIMARY KEY(id),
	FOREIGN KEY (country) REFERENCES countries (id),
	UNIQUE (user_name),
	UNIQUE (phone),
	UNIQUE (email)
);

CREATE TABLE posts(
	id uuid DEFAULT gen_random_uuid(), 
	"user" uuid NOT NULL, 
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY("user") REFERENCES users (id) 
);

CREATE TABLE photos (
	id uuid DEFAULT gen_random_uuid(), 
	post uuid,
	photo VARCHAR(225),
	PRIMARY KEY (id),
	FOREIGN KEY (post) REFERENCES posts (id)
);

CREATE TABLE comments (
	id uuid DEFAULT gen_random_uuid(), 
	"user" uuid, 
	post uuid,
	text TEXT, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	updated_at TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY ("user") REFERENCES users (id),
	FOREIGN KEY (post) REFERENCES posts (id)
);

CREATE TABLE likes(
	id uuid DEFAULT gen_random_uuid(), 
	"user" uuid, 
	post uuid,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY ("user") REFERENCES users (id),
	FOREIGN KEY (post) REFERENCES posts (id)
);

CREATE TABLE favorites (
	id uuid DEFAULT gen_random_uuid(), 
	"user" uuid, 
	post uuid,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY ("user") REFERENCES users (id),
	FOREIGN KEY (post) REFERENCES posts (id)
);

CREATE TABLE followers (
	id uuid DEFAULT gen_random_uuid(), 
	follower_user uuid,
	followed_user uuid,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY (follower_user) REFERENCES users (id),
	FOREIGN KEY (followed_user) REFERENCES users (id)
);

CREATE TABLE categories(
	id SERIAL, 
	categorie VARCHAR(20),
	PRIMARY KEY (id)
);

CREATE TABLE users_categories(
	id uuid DEFAULT gen_random_uuid(), 
	"user" uuid, 
	categorie INT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	deleted_at TIMESTAMP, 
	PRIMARY KEY (id),
	FOREIGN KEY ("user") REFERENCES users (id), 
	FOREIGN KEY (categorie) REFERENCES categories (id)
);



INSERT INTO countries (country)
VALUES
    ('Afghanistan'),
    ('Albania'),
    ('Algeria'),
    ('Andorra'),
    ('Angola'),
    ('Antigua and Barbuda'),
    ('Argentina'),
    ('Armenia'),
    ('Australia'),
    ('Austria'),
    ('Azerbaijan'),
    ('Bahamas'),
    ('Bahrain'),
    ('Bangladesh'),
    ('Barbados'),
    ('Belarus'),
    ('Belgium'),
    ('Belize'),
    ('Benin'),
    ('Bhutan'),
    ('Bolivia'),
    ('Bosnia and Herzegovina'),
    ('Botswana'),
    ('Brazil'),
    ('Brunei'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Cabo Verde'),
    ('Cambodia'),
    ('Cameroon'),
    ('Canada'),
    ('Central African Republic'),
    ('Chad'),
    ('Chile'),
    ('China'),
    ('Colombia'),
    ('Comoros'),
    ('Congo'),
    ('Costa Rica'),
    ('Croatia'),
    ('Cuba'),
    ('Cyprus'),
    ('Czech Republic'),
    ('Democratic Republic of the Congo'),
    ('Denmark'),
    ('Djibouti'),
    ('Dominica'),
    ('Dominican Republic'),
    ('East Timor'),
    ('Ecuador'),
    ('Egypt'),
    ('El Salvador'),
    ('Equatorial Guinea'),
    ('Eritrea'),
    ('Estonia'),
    ('Eswatini'),
    ('Ethiopia'),
    ('Fiji'),
    ('Finland'),
    ('France'),
    ('Gabon'),
    ('Gambia'),
    ('Georgia'),
    ('Germany'),
    ('Ghana'),
    ('Greece'),
    ('Grenada'),
    ('Guatemala'),
    ('Guinea'),
    ('Guinea-Bissau'),
    ('Guyana'),
    ('Haiti'),
    ('Honduras'),
    ('Hungary'),
    ('Iceland'),
    ('India'),
    ('Indonesia'),
    ('Iran'),
    ('Iraq'),
    ('Ireland'),
    ('Israel'),
    ('Italy'),
    ('Ivory Coast'),
    ('Jamaica'),
    ('Japan'),
    ('Jordan'),
    ('Kazakhstan'),
    ('Kenya'),
    ('Kiribati'),
    ('Kuwait'),
    ('Kyrgyzstan'),
    ('Laos'),
    ('Latvia'),
    ('Lebanon'),
    ('Lesotho'),
    ('Liberia'),
    ('Libya'),
    ('Liechtenstein'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Madagascar'),
    ('Malawi'),
    ('Malaysia'),
    ('Maldives'),
    ('Mali'),
    ('Malta'),
    ('Marshall Islands'),
    ('Mauritania'),
    ('Mauritius'),
    ('Mexico'),
    ('Micronesia'),
    ('Moldova'),
    ('Monaco'),
    ('Mongolia'),
    ('Montenegro'),
    ('Morocco'),
    ('Mozambique'),
    ('Myanmar'),
    ('Namibia'),
    ('Nauru'),
    ('Nepal'),
    ('Netherlands'),
    ('New Zealand'),
    ('Nicaragua'),
    ('Niger'),
    ('Nigeria'),
    ('North Korea'),
    ('North Macedonia'),
    ('Norway'),
    ('Oman'),
    ('Pakistan'),
    ('Palau'),
    ('Palestine'),
    ('Panama'),
    ('Papua New Guinea'),
    ('Paraguay'),
    ('Peru'),
    ('Philippines'),
    ('Poland'),
    ('Portugal'),
    ('Qatar'),
    ('Romania'),
    ('Russia'),
    ('Rwanda'),
    ('Saint Kitts and Nevis'),
    ('Saint Lucia'),
    ('Saint Vincent and the Grenadines'),
    ('Samoa'),
    ('San Marino'),
    ('Sao Tome and Principe'),
    ('Saudi Arabia'),
    ('Senegal'),
    ('Serbia'),
    ('Seychelles'),
    ('Sierra Leone'),
    ('Singapore'),
    ('Slovakia'),
    ('Slovenia'),
    ('Solomon Islands'),
    ('Somalia'),
    ('South Africa'),
    ('South Korea'),
    ('South Sudan'),
    ('Spain'),
    ('Sri Lanka'),
    ('Sudan'),
    ('Suriname'),
    ('Sweden'),
    ('Switzerland'),
    ('Syria'),
    ('Tajikistan'),
    ('Tanzania'),
    ('Thailand'),
    ('Togo'),
    ('Tonga'),
    ('Trinidad and Tobago'),
    ('Tunisia'),
    ('Turkey'),
    ('Turkmenistan'),
    ('Tuvalu'),
    ('Uganda'),
    ('Ukraine'),
    ('United Arab Emirates'),
    ('United Kingdom'),
    ('United States'),
    ('Uruguay'),
    ('Uzbekistan'),
    ('Vanuatu'),
    ('Vatican City'),
    ('Venezuela'),
    ('Vietnam'),
    ('Yemen'),
    ('Zambia'),
    ('Zimbabwe');

INSERT INTO categories ( categorie) VALUES ('Acción'),
('Aventura'), ('Arcade'), ('Deporte'), ('Estrategia'), ('Simulación'), ('Mesa'), ('Musicales')

